#cloud-config 
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages: 
- openjdk-8-jdk

runcmd: 
- echo "export SPARK_HOME=/opt/spark" >> /home/ubuntu/.bashrc
- echo "export PATH=$PATH:/opt/spark/bin:/opt/spark/sbin" >> /home/ubuntu/.bashrc
- curl -O https://dlcdn.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz > /home/ubuntu/spark-3.2.1-bin-hadoop3.2.tgz
- tar xvf /home/ubuntu/spark-3.2.1-bin-hadoop3.2.tgz
- rm /home/ubuntu/spark-3.2.1-bin-hadoop3.2.tgz
- mv /home/ubuntu/spark-3.2.1-bin-hadoop3.2/ /opt/spark
- source /home/ubuntu/.bashrc
- start-worker.sh spark://<MASTER_NODE_PRIVATE_IP>:7077