#cloud-config 
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages: 
- openjdk-8-jdk
- python3-pip
- scala

runcmd:
- echo "export PYSPARK_PYTHON=python3" >> /home/ubuntu/.bashrc
- python3 -m pip install pyspark==3.2.1 --no-cache-dir
- echo "export PATH=$PATH:/home/ubuntu/.local/bin" >> /home/ubuntu/.bashrc
- source /home/ubuntu/.bashrc
- echo "SPARK_HOME=/home/ubuntu/.local/lib/python3.8/site-packages/pyspark" >> /home/ubuntu/.bashrc
- apt-get install gnupg
- wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add -
- echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list
- apt-get update
- apt-get install -y mongodb-org

