#cloud-config 
# NOTE THIS DOES NOT WORK YET
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages: 
- openjdk-8-jdk
- python3-pip
- scala

runcmd:
- echo "export PYSPARK_PYTHON=python3" >> /home/ubuntu/.bashrc
- python3 -m pip install pyspark==3.2.1 --no-cache-dir
- python3 -m pip install pandas 
- echo "export PATH=$PATH:/home/ubuntu/.local/bin" >> /home/ubuntu/.bashrc
- source /home/ubuntu/.bashrc
- echo "SPARK_HOME=/home/ubuntu/.local/lib/python3.8/site-packages/pyspark" >> /home/ubuntu/.bashrc
- python3 -m pip install matplotlib 
- python3 -m pip install jupyterlab
#- python3 -m jupyterlab
